version: '3.8'

services:
  backend-api:
    container_name: backend-api
    build:
      context: ./src/backend_api
    ports:
      - "80:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_POOL_SIZE: ${DB_POOL_SIZE}
      PYTHONPATH: /app/
      ROOT_DIR: /app/
  notebook:
    container_name: notebook
    build:
      context: ./src/backend_api
      dockerfile: Dockerfile-notebook
    depends_on:
      - backend-api
    ports:
      - "8888:8888"
    environment:
      PYTHONPATH: /app/