version: '3.8'

services:
  backend-api:
    container_name: backend-api
    build:
      context: .
      dockerfile: ./src/backend_api/Dockerfile
    depends_on:
      - db-timescale
    ports:
      - "80:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_POOL_SIZE: ${DB_POOL_SIZE}
      PYTHONPATH: /app/
      ROOT_DIR: /app/
  notebook:
    container_name: notebook
    build:
      context: .
      dockerfile: ./src/backend_api/Dockerfile-notebook
    depends_on:
      - backend-api
      - db-timescale
      - spark-master
    ports:
      - "8888:8888"
    environment:
      PYTHONPATH: /app/
    volumes:
      - ./notebook:/opt/notebooks
  db-timescale:
    container_name: db-timescale
    image: timescale/timescaledb:latest-pg12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./src/db_timescale/storage:/var/lib/postgresql/data
  # spark
  spark-master:
    build:
      context: ./src/backend_pipeline/spark/
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - HOSTNAME=spark-master
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=0.0.0.0
      # - SPARK_WORKER_CORES=2
      # - SPARK_WORKER_MEMORY=500m
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      # - JAVA_HOME: /opt/bitnami/java
      # - SPARK_HOME: /opt/bitnami/spark
    volumes:
      - ./notebook:/opt/notebooks
    ports:
      - '8080:8080'
      - '7077:7077'
  spark-worker-1:
    build:
      context: ./src/backend_pipeline/spark/
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./notebook:/opt/notebooks
  # grafana
  frontend:
    container_name: frontend
    image: grafana/grafana:latest
    depends_on:
        - db-timescale
    ports:
        - 3000:3000
    volumes:
        - ./src/frontend/data:/var/lib/grafana
        - ./src/frontend/config:/etc/grafana/
        - ./src/frontend/log:/var/log/grafana
        - ./src/frontend/provisioning:/etc/grafana/provisioning
        - ./src/frontend/plugins:/var/lib/grafana/plugins
    environment:
      # grafana internal vars
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: db-timescale:${DB_PORT}
      GF_DATABASE_NAME: ${DB_NAME}
      GF_DATABASE_USER: ${DB_USER}
      GF_DATABASE_PASSWORD: ${DB_PASS}
      GF_DATABASE_SSL_MODE: disable
      #datasource vars
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

