{
 "title": "2020 US Election real-time sentiment analysis",
 "time": { "from": "2020-10-15T04:00:00.000Z", "to": "2020-11-09T04:59:59.000Z" },
 "panels": [
  {
   "title": "Biden",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://media-cldnry.s-nbcnews.com/image/upload/t_fit-2000w,f_auto,q_auto:best/newscms/2020_14/3293586/200402-joe-biden-cs-345p.jpg\"/></center>\n"
   }
  },
  {
   "title": "Daily tweet Sentiment status in the US ",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 16, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH TRUMP AS (\n  SELECT\n    distinct on (state_code)\n    $__timeGroupAlias(created_at,'1d'),\n    avg(score) AS \"score\",\n    state_code AS \"state_code\",\n    state AS \"state\"\n  FROM donaldtrump_tweets\n  WHERE\n    $__timeFilter(created_at)\n    AND state_code IS NOT NULL\n  GROUP BY 1, 3, 4\n  ORDER BY state_code, \"time\" DESC\n), BIDEN AS (\n  SELECT\n    distinct on (state_code)\n    $__timeGroupAlias(created_at,'1d'),\n    avg(score) AS \"score\",\n    state_code AS \"state_code\",\n    state AS \"state\"\n  FROM joebiden_tweets\n  WHERE\n    $__timeFilter(created_at)\n    AND state_code IS NOT NULL\n  GROUP BY 1, 3, 4\n  ORDER BY state_code, \"time\" DESC\n)\nSELECT\n  TRUMP.\"time\",\n  TRUMP.\"state_code\",\n  TRUMP.\"state\",\n  TRUMP.\"score\" - BIDEN.\"score\" AS \"polarity\"\nFROM\n  TRUMP\nINNER join\n  BIDEN\nON TRUMP.\"time\" = BIDEN.\"time\" AND TRUMP.\"state\" = BIDEN.\"state\""
    }
   ]
  },
  {
   "title": "Trump",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://media-cldnry.s-nbcnews.com/image/upload/t_fit-2000w,f_auto,q_auto:best/newscms/2020_29/3397534/2000716-donald-trump-se-1215p.jpg\"/></center>\n"
   }
  },
  {
   "title": "Biden hourly average sentiment score ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,'1h'),\n  avg(score) AS \"sentiment score\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Trump hourly average sentiment score ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  avg(score) AS \"sentiment score\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tweets Polarity",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH TRUMP AS (\n  SELECT\n    $__timeGroupAlias(created_at,'1h'),\n    avg(score) AS \"score\"\n  FROM donaldtrump_tweets\n  WHERE\n    $__timeFilter(created_at)\n  GROUP BY 1\n  ORDER BY 1 DESC LIMIT 1\n), BIDEN AS (\n  SELECT\n    $__timeGroupAlias(created_at,'1h'),\n    avg(score) AS \"score\"\n  FROM joebiden_tweets\n  WHERE\n    $__timeFilter(created_at)\n  GROUP BY 1\n  ORDER BY 1 DESC LIMIT 1\n)\nSELECT\n  TRUMP.\"time\",\n  TRUMP.\"score\" - BIDEN.\"score\" AS \"polarity\"\nFROM\n  TRUMP\nINNER join\n  BIDEN\nON TRUMP.\"time\" = BIDEN.\"time\""
    }
   ]
  },
  {
   "title": "Current time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  max(score) as \"sentiment score\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sentiment score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(joebiden_tweets.created_at,12h),\n  avg(joebiden_tweets.score) AS \"Biden sentiment score\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(joebiden_tweets.created_at)\nGROUP BY 1\nORDER BY 1;\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,12h),\n  avg(score) AS \"Trump sentiment score\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Total likes count per 6 hours ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  sum(retweet_count) AS \"Biden total likes count\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  sum(retweet_count) AS \"Trump total likes count\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total retweet count per 6 hours ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  sum(retweet_count) AS \"Biden total retweet count\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  sum(retweet_count) AS \"Trump total retweet count\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total tweets count per 6 hours ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  count(DISTINCT tweet_ID) AS \"Biden total tweet count\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  count(DISTINCT tweet_ID) AS \"Trump total tweet count\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total unique user count per 6 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  count(DISTINCT user_ID) AS \"Biden total unique user count\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  count(DISTINCT user_ID) AS \"Trump total unique user count\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Democrat",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "options": {
    "content": "# <center><span style=\"color:DodgerBlue\">Build back better</span></center>\n"
   }
  },
  {
   "title": "Total daily retweets count and likes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,24h),\n  sum(retweet_count) AS \"Total retweet count\",\n  sum(likes) AS \"Total Likes count\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total daily retweets count and likes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,24h),\n  sum(retweet_count) AS \"Total retweet count\",\n  sum(likes) AS \"Total Likes count\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Republican ",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "options": {
    "content": "# <center><span style=\"color:Crimson\"> Make America Great Again</span></center>"
   }
  },
  {
   "title": "Total daily tweets and unique user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,24h),\n  COUNT(DISTINCT tweet_id) AS \"Total tweet count\",\n  COUNT(DISTINCT user_id) AS \"Total Unique user\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total daily tweets and unique user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,24h),\n  COUNT(tweet_id) AS \"Total tweet count\",\n  COUNT(DISTINCT user_id) AS \"Total Unique user\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}