{
 "title": "2020 US Election real-time sentiment analysis dashboard",
 "time": { "from": "2020-10-15T04:00:00.000Z", "to": "2020-11-09T04:59:59.000Z" },
 "panels": [
  {
   "title": "Democrat",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "# <span style=\"color:DodgerBlue\">Build back better</span>\n"
   }
  },
  {
   "title": "Current time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  max(score) as \"sentiment score\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Republican ",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "# <span style=\"color:Crimson\"> Make America Great Again</span>"
   }
  },
  {
   "title": "Biden",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": {
    "content": "<img src =\"https://img.i-scmp.com/cdn-cgi/image/fit=contain,width=1098,format=auto/sites/default/files/styles/1200x800/public/d8/images/methode/2020/11/17/f2d3be6a-27dd-11eb-bf26-f2b76f37a526_image_hires_063003.jpg?itok=WaNIxEvo&v=1605565815\"/>\n"
   }
  },
  {
   "title": "Biden hourly average sentiment score ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,'1h'),\n  avg(score) AS \"sentiment score\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Trump hourly average sentiment score ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  avg(score) AS \"sentiment score\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Trump",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "options": {
    "content": "   ![Image](https://assets.bwbx.io/images/users/iqjWHBFdfxIU/i9YFn9RunLSM/v1/1400x-1.jpg)       "
   }
  },
  {
   "title": "Total daily retweet count and likes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,24h),\n  sum(retweet_count) AS \"Total retweet count\",\n  sum(likes) AS \"Total Likes count\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sentiment score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(joebiden_tweets.created_at,12h),\n  avg(joebiden_tweets.score) AS \"Biden sentiment score\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(joebiden_tweets.created_at)\nGROUP BY 1\nORDER BY 1;\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,12h),\n  avg(score) AS \"Trump sentiment score\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Total daily retweets count and likes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,24h),\n  sum(retweet_count) AS \"Total retweet count\",\n  sum(likes) AS \"Total Likes count\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total daily tweets and unique user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,24h),\n  COUNT(DISTINCT tweet_id) AS \"Total tweet count\",\n  COUNT(DISTINCT user_id) AS \"Total Unique user\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total daily tweets and unique user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,24h),\n  COUNT(tweet_id) AS \"Total tweet count\",\n  COUNT(DISTINCT user_id) AS \"Total Unique user\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}