{
 "title": "2020 US Election real-time sentiment analysis",
 "time": { "from": "2020-10-15T04:00:00.000Z", "to": "2020-11-08T05:00:00.000Z" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://5003project.blob.core.windows.net/data/biden.jpg\"/></center>\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1m),\n  max(score) as \"sentiment score\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://5003project.blob.core.windows.net/data/trump.jpg\"/></center>\n"
   }
  },
  {
   "title": "Daily tweet Sentiment status in the US ",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH TRUMP AS (\n  SELECT\n    distinct on (state_code)\n    $__timeGroupAlias(created_at,'1d'),\n    avg(score) AS \"score\",\n    state_code AS \"state_code\",\n    state AS \"state\"\n  FROM donaldtrump_tweets\n  WHERE\n    $__timeFilter(created_at)\n    AND state_code IS NOT NULL\n  GROUP BY 1, 3, 4\n  ORDER BY state_code, \"time\" DESC\n), BIDEN AS (\n  SELECT\n    distinct on (state_code)\n    $__timeGroupAlias(created_at,'1d'),\n    avg(score) AS \"score\",\n    state_code AS \"state_code\",\n    state AS \"state\"\n  FROM joebiden_tweets\n  WHERE\n    $__timeFilter(created_at)\n    AND state_code IS NOT NULL\n  GROUP BY 1, 3, 4\n  ORDER BY state_code, \"time\" DESC\n)\nSELECT\n  TRUMP.\"time\",\n  TRUMP.\"state_code\",\n  TRUMP.\"state\",\n  TRUMP.\"score\" - BIDEN.\"score\" AS \"polarity\"\nFROM\n  TRUMP\nINNER join\n  BIDEN\nON TRUMP.\"time\" = BIDEN.\"time\" AND TRUMP.\"state\" = BIDEN.\"state\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "options": {
    "content": "# <center><span style=\"color:DodgerBlue\">Build Back Better</span></center>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 10 },
   "options": {
    "content": "# <center><span style=\"color:Crimson\">Make America Great Again</span></center>"
   }
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,'1d'),\n  avg(score) AS \"sentiment score\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at, '1d'),\n  avg(score) AS \"sentiment score\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH TRUMP AS (\n  SELECT\n    $__timeGroupAlias(created_at,'1d'),\n    avg(score) AS \"score\"\n  FROM donaldtrump_tweets\n  WHERE\n    $__timeFilter(created_at)\n  GROUP BY 1\n  ORDER BY 1 DESC LIMIT 1\n), BIDEN AS (\n  SELECT\n    $__timeGroupAlias(created_at,'1d'),\n    avg(score) AS \"score\"\n  FROM joebiden_tweets\n  WHERE\n    $__timeFilter(created_at)\n  GROUP BY 1\n  ORDER BY 1 DESC LIMIT 1\n)\nSELECT\n  TRUMP.\"time\",\n  TRUMP.\"score\" - BIDEN.\"score\" AS \"polarity\"\nFROM\n  TRUMP\nINNER join\n  BIDEN\nON TRUMP.\"time\" = BIDEN.\"time\""
    }
   ]
  },
  {
   "title": "Sentiment score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(joebiden_tweets.created_at,'1d'),\n  avg(joebiden_tweets.score) AS \"Biden sentiment score\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(joebiden_tweets.created_at)\nGROUP BY 1\nORDER BY 1;\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,'1d'),\n  avg(score) AS \"Trump sentiment score\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Total tweets count per 6 hours ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  count(DISTINCT tweet_ID) AS \"Biden total tweet count\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  count(DISTINCT tweet_ID) AS \"Trump total tweet count\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total likes count per 6 hours ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  sum(retweet_count) AS \"Biden total likes count\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  sum(retweet_count) AS \"Trump total likes count\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total unique user count per 6 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  count(DISTINCT user_ID) AS \"Biden total unique user count\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  count(DISTINCT user_ID) AS \"Trump total unique user count\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total retweet count per 6 hours ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  sum(retweet_count) AS \"Biden total retweet count\"\nFROM joebiden_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,6h),\n  sum(retweet_count) AS \"Trump total retweet count\"\nFROM donaldtrump_tweets\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}